server: <pve_ip>
user: <user>
realm: <realm>
password: <password>
spice_client_path: '<path to client executable'
custom_hosts:
  <pve_fqdn>: <pve_ip>
api_syntax:
  - pvesh
  - proxmoxer
  - curl

## Remote Access Protocol Mapping ##
#connect_commands:
#  spice: "remote-viewer"
#  rdp: "remmina -c rdp://{ip}"
#  ssh: "gnome-terminal -- ssh {user}@{ip}"
#  ssh_terminator: 'terminator -e "ssh -p {port} {user}@{ip}"'