## Login Information ##
## optional, any of these fields can be passed as command line args
node: <node_ip>
user: <user>
realm: <realm>
password: <password>

# Required for SPICE connection if pve node fqdn is not DNS or hosts file resolvable
custom_hosts:
  <pve_fqdn>: <pve_ip>

## API Syntax ##
## optional, if you want to print syntax for specific API methods
api_syntax:
  - pvesh
  - proxmoxer
  - curl

## Remote Access Protocol Mapping ##
## optional, if you want to be able to remotely connect to VMs from this client
#connect_commands:
#  spice: "remote-viewer"
#  rdp: "remmina -c rdp://{ip}"
#  ssh: "gnome-terminal -- ssh {user}@{ip}"
#  ssh_terminator: 'terminator -e "ssh -p {port} {user}@{ip}"'